@host = http://localhost:3001/api

###
POST {{host}}/auth/register
Content-Type: application/json

{
    "Name":"Simbi Sam",
    "Email":"simbi@gmail.com",
    "Password":"12345"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
    "Email": "simbi@gmail.com",
    "Password":"12345"
}